theme: minima

title: Dobby's blog
author: Dobby233Liu

description: > # this means to ignore newlines until "baseurl:"
  I made this simple blog to record something. Using jekyll's Minima theme. This theme is jekyll's first theme. Orignal version is archive by me.

# Social
github_username:  Dobby233Liu
